new test on push for required ci/cd tag

diff --git a/.github/workflows/black.yml b/.github/workflows/black.yml
--- a/.github/workflows/black.yml
+++ b/.github/workflows/black.yml
@@ -3,8 +3,42 @@ name: Lint
 on: [pull_request]
 
 jobs:
-  lint:
+  python_format:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: psf/black@stable
+
+  get_job_files:
+    runs-on: ubuntu-latest
+    environment: development
+    outputs:
+      matrix: ${{ steps.repo_files.outputs.link_list }}
+    steps:
+      - name: Get repo job files
+        id: repo_files
+        run: >
+          link_list=$(curl \
+            -L 'https://api.github.com/repos/pennfoster/databricks-pipelines/contents/orchestration/dbricks_jobs?ref=cicd%2Ftest_jobs_in_pr' \
+            -H 'Accept: application/vnd.github+json' \
+            -H 'X-GitHub-Api-Version: 2022-11-28' |
+            jq -r [".[].download_url"])
+          echo $link_list >> "$GITHUB_OUTPUT"
+  
+  assure_cicd_tag:
+    runs-on: ubuntu-latest
+    environment: development
+    needs: get_job_files
+    strategy:
+      matrix:
+        job_content: ${{ fromJson(needs.get_job_files.outputs.matrix) }}
+    steps:
+      - name: Check job tags
+        run: >
+          CICD_TAG=$(curl -L ${{ matrix.job_content }} |
+            jq -r '.settings.tags.workflow')
+          if [ "$CICD_TAG" != "CI/CD" ]
+            then
+              echo "Job @ ${{ matrix.job_content }} missing required \"workflow: CI/CD\" tag"
+              exit 1
+          fi
