better visibility

diff --git a/.github/workflows/PR_verify_job_format.yaml b/.github/workflows/PR_verify_job_format.yaml
--- a/.github/workflows/PR_verify_job_format.yaml
+++ b/.github/workflows/PR_verify_job_format.yaml
@@ -38,24 +38,25 @@ jobs:
         run: >
           DOWNLOAD_URL=$(curl -L "${{ matrix.job_content }}" | jq -r .download_url);
           JOB_VARS=$(curl -L "$DOWNLOAD_URL");
+          echo "job_name=$(echo "$JOB_VARS" | jq -r '.name')" >> "$GITHUB_OUTPUT"
           echo "cicd_tag=$(echo "$JOB_VARS" | jq -r '.tags.workflow')" >> "$GITHUB_OUTPUT";
           echo "task_filepaths='$(echo "$JOB_VARS" | jq -c ['.tasks[].notebook_task.notebook_path'])'" >> "$GITHUB_OUTPUT";
       - name: Assure Correct Tag
         run: >
           if [ "${{ steps.job_vars.outputs.cicd_tag }}" != "CI/CD" ]
             then
-              echo $CICD_TAG
-              echo "CI/CD"
-              echo "Job @ ${{ matrix.job_content }} missing required \"workflow: CI/CD\" tag"
-              exit 1
+              echo "Job ${{ steps.job_vars.outputs.job_name }} is missing required \"workflow: CI/CD\" tag";
+              exit 1;
           fi
       - name: Assure Correst Filepaths
         run: >
           for FP in $(echo ${{ steps.job_vars.outputs.task_filepaths }} | jq -r .[]);
             do
-                if [[ $FP =~ ^\/Repos\/[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}\/.*$ ]]
-                    then
-                    echo "Notebook filepath is set to personal workspace"
-                    exit 1
-                fi
+              if [[ $FP =~ ^\/Repos\/[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}\/.*$ ]]
+                then
+                  echo "In Job ${{ steps.job_vars.outputs.job_name }}:";
+                  echo "Notebook filepath is set to personal workspace:";
+                  echo $FP;
+                  exit 1
+              fi
             done
